name: CTFTime

on:
  schedule:
    - cron:  '*/10 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DiscordWebhookUrl }}
        run: |
          python CTFtime-Discord-hooks/CTFtimeDiscordHooks.py -w "$DISCORD_WEBHOOK_URL" -d 10
